export const authConstants = {
  SUBSCRIBE_REQUEST: "SUBSCRIBE_REQUEST",
  SUBSCRIBE_SUCCESS: "SUBSCRIBE_SUCCESS",
  SUBSCRIBE_FAILURE: "SUBSCRIBE_FAILURE",
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  LOGOUT: "USER_LOGOUT",
  CHANGE_REQUEST: "USER_CHANGE_REQUEST",
  CHANGE_SUCCESS: "USER_CHANGE_SUCCESS",
  CHANGE_FAILURE: "USER_CHANGE_FAILURE"
};
