export const notesConstants = {
  ADD_NOTE: "NOTES_ADD_NOTE",
  DELETE_NOTE: "NOTES_DELETE_NOTE",
  GETALL_REQUEST: "NOTES_GETALL_REQUEST",
  GETALL_SUCCESS: "NOTES_GETALL_SUCCESS",
  GETALL_FAILURE: "NOTES_GETALL_FAILURE",
  POST_REQUEST: "NOTES_POST_REQUEST",
  POST_SUCCESS: "NOTES_POST_SUCCESS",
  POST_FAILURE: "NOTES_POST_FAILURE",
  DEL_FAILURE: "NOTES_DEL_FAILURE",
  GET_USERS_LIST: "NOTES_GET_USERS"
};
