export const usersConstants = {
  GETGROUPLIST_REQUEST: "NOTES_GETGROUPLIST_REQUEST",
  GETGROUPLIST_SUCCESS: "NOTES_GETGROUPLIST_SUCCESS",
  GETGROUPLIST_FAILURE: "NOTES_GETGROUPLIST_FAILURE",
  POSTGROUPLIST_REQUEST: "NOTES_POSTGROUPLIST_REQUEST",
  POSTGROUPLIST_SUCCESS: "NOTES_POSTGROUPLIST_SUCCESS",
  POSTGROUPLIST_FAILURE: "NOTES_POSTGROUPLIST_FAILURE",
  SELECT_GROUP_NOTE: "SELECT_GROUP_NOTE",
  SELECT_MY_NOTES: "SELECT_MY_NOTES"
};
