version: 2
jobs:
  build-server:
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/notes
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ( cd server && go build . )
      - persist_to_workspace:
          root: ./
          paths:
            - ./server
  client-install:
    docker:
      - image: circleci/node:11
    working_directory: /home/circleci/notes
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm ci --prefix client
      - persist_to_workspace:
          root: ./
          paths:
            - ./client
  create-app:
    docker:
      - image: circleci/node:11
    steps:
      - attach_workspace:
          at: ./
      - run:
          command: |
            cd server
            openssl genrsa -out key.pem 2048
            openssl rsa -in key.pem -outform PEM -pubout -out public.pem
      - run: node client/scripts/setup.js
      - run: npm run build --prefix client
      - persist_to_workspace:
          root: ./
          paths:
            - ./client
            - ./server
  test-e2e:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - attach_workspace:
          at: ./
      - run:
          command: |
            ( cd server ; ./server & )
            ( cd client ; npm i serve ; node_modules/.bin/serve -s build -l 3000 & )
            cd client && node_modules/.bin/cypress install && node_modules/.bin/cypress run
      - store_artifacts:
          path: client/cypress/videos
      - store_artifacts:
          path: client/cypress/screenshots
workflows:
  version: 2
  build:
    jobs:
      - build-server
      - client-install
      - create-app:
          requires:
            - build-server
            - client-install
      - test-e2e:
          requires:
            - create-app
