version: 2
jobs:
  build-server:
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/notes
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ( cd server && go build . )
      - persist_to_workspace:
          root: ./
          paths:
            - ./server
  build-client:
    docker:
      - image: circleci/node:11
    working_directory: /home/circleci/notes
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm i --prefix client
      - run: npm build --prefix client
      - persist_to_workspace:
          root: ./
          paths:
            - ./client
workflows:
  version: 2
  build:
    jobs:
      - build-server
      - build-client
