apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-client-deployment
spec:
  selector:
    matchLabels:
      app: note-client
  template:
    metadata:
      labels:
        app: note-client
    spec:
      containers:
      - name: note-client
        image: node-frontend
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: note-client-service
spec:
  type: LoadBalancer
  selector:
    app: note-client
  ports:
  - port: 3000
    targetPort: 8080

