apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-client
spec:
  selector:
    matchLabels:
      app: notes-client
  template:
    metadata:
      labels:
        app: notes-client
    spec:
      containers:
        - name: notes-client
          image: gcr.io/peps-146814/notes-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: notes-client
spec:
  type: LoadBalancer
  loadBalancerIP: 34.76.229.203
  selector:
    app: notes-client
  ports:
    - port: 80
      targetPort: 5000
