apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-server
spec:
  selector:
    matchLabels:
      app: notes-server
  template:
    metadata:
      labels:
        app: notes-server
    spec:
      containers:
        - name: notes-server
          image: gcr.io/peps-146814/notes-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notes-server
spec:
  type: LoadBalancer
  loadBalancerIP: 35.205.229.100
  selector:
    app: notes-server
  ports:
    - port: 80
      targetPort: 8080
